# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Group-Buying' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Group-Buying
  pod 'AFNetworking', '~> 3.0'
   pod 'SDWebImage', '~>3.8'
   pod 'Masonry'
end
